# Generated by Django 4.0.5 on 2022-06-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubbus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
