# Generated by Django 4.0.5 on 2022-08-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dubbus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestops',
            options={},
        ),
        migrations.AlterModelOptions(
            name='routesupdated',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stops',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stoptimesupdated',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={},
        ),
    ]
