# Generated by Django 4.0.5 on 2022-08-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubbus', '0004_alter_routestops_options_alter_routesupdated_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('description_code', models.CharField(blank=True, max_length=10, null=True)),
                ('conditions', models.CharField(blank=True, max_length=80, null=True)),
                ('weather_type', models.CharField(blank=True, max_length=2, null=True)),
                ('date_time', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'forecast',
            },
        ),
    ]
