# Generated by Django 4.0.5 on 2022-08-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dubbus', '0005_forecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'managed': False},
        ),
    ]
