# Generated by Django 4.0.5 on 2022-08-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dubbus', '0006_alter_forecast_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={},
        ),
    ]
